 HEAD
name: CI/CD Pipeline

on:
  push:
    branches:
      - feature/**
  pull_request:
    branches:
      - develop

permissions:
  contents: write  # Επιτρέπει το push στο repository
  pull-requests: write  # Επιτρέπει τη διαχείριση Pull Requests

jobs:
  build:
    name: Build and Compile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean compile

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Unit Tests
        run: mvn test

  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Integration Tests
        run: mvn verify

  merge-to-develop:
    name: Merge Feature Branch to Develop
    runs-on: ubuntu-latest
    needs: integration-tests
    if: github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Merge feature branch into develop
        run: |
          git checkout develop
          git merge --no-ff ${{ github.ref_name }} -m "Auto-merged by GitHub Actions"
          git push origin develop

name: CI/CD Pipeline

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - "feature/**" # Εκτελείται μόνο για θεματικά branches
      - "develop"

jobs:
  build:
    name: Build & Compile Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install -DskipTests

  unit-tests:
    name: Unit Testing
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Unit Tests
        run: mvn test -Dgroups="unit"

  integration-tests:
    name: Integration & API Testing
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Integration & API Tests
        run: mvn verify -Dgroups="integration"

  merge-to-develop:
    name: Merge Branch to Develop
    needs: integration-tests
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge to Develop
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git fetch --all
          git checkout develop
          git merge --no-ff --allow-unrelated-histories feature/ci-cd-pipeline -m "Auto-merged by GitHub Actions"
          git push origin develop
 feature/ci-cd-pipeline
